### ISSUE TITLE
Implementation

### ISSUE THREAD

**Issue by ljcleyba** [DimaKoz/meat-grinder#5]
Hi. Can you please help with a step by step implementation of this? Thank you

**Comment by dapate** [comment]
Saya ingin me root hp saya ?

> Hai. Bisakah Anda membantu dengan implementasi langkah demi langkah ini? Terima kasih

Saya ingin me root hp saya

**Comment by dapate** [comment]
#6 #3 #2 #1

**Comment by DimaKoz** [comment]
@dapate thank you 👍🏻
