### ISSUE TITLE
Google Play url is broken

### ISSUE THREAD

**Issue by Fi5t** [DimaKoz/meat-grinder#7]
Hello! When I try to open your demo application url I get "404 Not found error". Can you provide a valid link?

**Comment by DimaKoz** [comment]
Nope. I had no time to update the app and Google deleted it from Google Play. I think I can upload the app to Github soon.

**Comment by DimaKoz** [comment]
https://github.com/DimaKoz/meat-grinder/blob/master/apk/NativeRootChecker_1_0_0.apk
